### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by kalle303** [Coinffeine/coinffeine#256]
I just downloaded coinffeine-0.8.0_win64.exe on my Win 7 64x PC. Installed without issues(although the splash screen always ontop was disturbing) and first time i run the application i get this error:
"An unexpected error was thrown while starting Coinffeine app. If the error persists please report.."
The exception stacktrace(First run):

java.lang.RuntimeException: cannot start coinffeine app
	at coinffeine.peer.api.impl.DefaultCoinffeineApp$$anonfun$start$1.applyOrElse(DefaultCoinffeineApp.scala:54)
	at coinffeine.peer.api.impl.DefaultCoinffeineApp$$anonfun$start$1.applyOrElse(DefaultCoinffeineApp.scala:53)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.processBatch$1(BatchingExecutor.scala:67)
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:82)
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59)
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at akka.dispatch.BatchingExecutor$Batch.run(BatchingExecutor.scala:58)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:401)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.RuntimeException: Requesting Start(()) to Actor[akka://app-wallet-248/user/peer#-1559788454]
	at coinffeine.common.akka.AskPattern$AskRequestBuilder$$anonfun$wrapErrors$1.applyOrElse(AskPattern.scala:61)
	at coinffeine.common.akka.AskPattern$AskRequestBuilder$$anonfun$wrapErrors$1.applyOrElse(AskPattern.scala:55)
	... 15 more
Caused by: coinffeine.common.akka.AskPattern$AskRequestBuilder$$anonfun$wrapErrors$1$$anon$1: Requesting Start(()) to Actor[akka://app-wallet-248/user/peer/paymentProcessor#-1266285553]: timeout of 10 seconds waiting for response (Ask timed out on [Actor[akka://app-wallet-248/user/peer/paymentProcessor#-1266285553]] after [10000 ms])

Second time i run the applicaion(and all future attempts) i get this slightly different error:
The exception stacktrace(second run):

java.lang.RuntimeException: cannot start coinffeine app
	at coinffeine.peer.api.impl.DefaultCoinffeineApp$$anonfun$start$1.applyOrElse(DefaultCoinffeineApp.scala:54)
	at coinffeine.peer.api.impl.DefaultCoinffeineApp$$anonfun$start$1.applyOrElse(DefaultCoinffeineApp.scala:53)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.processBatch$1(BatchingExecutor.scala:67)
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:82)
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59)
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at akka.dispatch.BatchingExecutor$Batch.run(BatchingExecutor.scala:58)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:401)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.RuntimeException: Requesting Start(()) to Actor[akka://app-wallet-248/user/peer#1536325463]
	at coinffeine.common.akka.AskPattern$AskRequestBuilder$$anonfun$wrapErrors$1.applyOrElse(AskPattern.scala:61)
	at coinffeine.common.akka.AskPattern$AskRequestBuilder$$anonfun$wrapErrors$1.applyOrElse(AskPattern.scala:55)
	... 16 more
Caused by: coinffeine.common.akka.AskPattern$AskRequestBuilder$$anonfun$wrapErrors$1$$anon$1: Requesting Start(()) to Actor[akka://app-wallet-248/user/peer/paymentProcessor#1164345645]: timeout of 10 seconds waiting for response (Ask timed out on [Actor[akka://app-wallet-248/user/peer/paymentProcessor#1164345645]] after [10000 ms])

**Comment by sortega** [comment]
Hello kalle303,

Can you take the application log (at `%APPDATA%\Coinffeine\Coinffeine.log` and send it to support@coinffeine.com?

Many thanks
