### ISSUE TITLE
Building error / Unable to resolve dependency.

### ISSUE THREAD

**Issue by ayoubmtd** [Coinffeine/coinffeine#257]
Hello, when I tried to build the project, I get a dependency not found problem. at sbt-javafx;0.6.2-coinffeine. when I tried to download it manually the folder on the server was empty. Can you help me fix this problem ?

[info] Resolving no.vedaadata#sbt-javafx;0.6.2-coinffeine ...
[error] SERVER ERROR: Server Error url=http://repository.coinffeine.com/content/repositories/third-party/no/vedaadata/sbt-javafx_2.10_0.13/0.6.2-coinffeine/sbt-javafx-0.6.2-coinffeine.pom
[error] Unable to find credentials for [Sonatype Nexus Repository Manager @ oss.sonatype.org].
[warn] 	module not found: no.vedaadata#sbt-javafx;0.6.2-coinffeine
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/no.vedaadata/sbt-javafx/scala_2.10/sbt_0.13/0.6.2-coinffeine/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/no.vedaadata/sbt-javafx/scala_2.10/sbt_0.13/0.6.2-coinffeine/ivys/ivy.xml
[warn] ==== local: tried
[warn]   /home/ayoub/.ivy2/local/no.vedaadata/sbt-javafx/scala_2.10/sbt_0.13/0.6.2-coinffeine/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/no/vedaadata/sbt-javafx_2.10_0.13/0.6.2-coinffeine/sbt-javafx-0.6.2-coinffeine.pom
[warn] ==== coinffeine-third-party: tried
[warn]   http://repository.coinffeine.com/content/repositories/third-party/no/vedaadata/sbt-javafx_2.10_0.13/0.6.2-coinffeine/sbt-javafx-0.6.2-coinffeine.pom
[warn] ==== sonatype-releases: tried
[warn]   https://oss.sonatype.org/service/local/staging/deploy/maven2/no/vedaadata/sbt-javafx_2.10_0.13/0.6.2-coinffeine/sbt-javafx-0.6.2-coinffeine.pom
[warn] ==== sonatype-public: tried
[warn]   https://oss.sonatype.org/content/repositories/public/no/vedaadata/sbt-javafx_2.10_0.13/0.6.2-coinffeine/sbt-javafx-0.6.2-coinffeine.pom
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/no.vedaadata/sbt-javafx/scala_2.10/sbt_0.13/0.6.2-coinffeine/ivys/ivy.xml
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: no.vedaadata#sbt-javafx;0.6.2-coinffeine: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn] 		no.vedaadata:sbt-javafx:0.6.2-coinffeine (scalaVersion=2.10, sbtVersion=0.13)
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		no.vedaadata:sbt-javafx:0.6.2-coinffeine (scalaVersion=2.10, sbtVersion=0.13) (/home/ayoub/code/coinffeine/project/plugins.sbt#L18-19)
[warn] 		  +- default:coinffeine-build:0.1-SNAPSHOT (scalaVersion=2.10, sbtVersion=0.13)
sbt.ResolveException: unresolved dependency: no.vedaadata#sbt-javafx;0.6.2-coinffeine: not found
	at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:291)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:188)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:165)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
	at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:132)
	at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
	at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
	at xsbt.boot.Using$.withResource(Using.scala:10)
	at xsbt.boot.Using$.apply(Using.scala:9)
	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
	at xsbt.boot.Locks$.apply0(Locks.scala:31)
	at xsbt.boot.Locks$.apply(Locks.scala:28)
	at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
	at sbt.IvySbt.withIvy(Ivy.scala:127)
	at sbt.IvySbt.withIvy(Ivy.scala:124)
	at sbt.IvySbt$Module.withModule(Ivy.scala:155)
	at sbt.IvyActions$.updateEither(IvyActions.scala:165)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1369)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1365)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$87.apply(Defaults.scala:1399)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$87.apply(Defaults.scala:1397)
	at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:37)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1402)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1396)
	at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:60)
	at sbt.Classpaths$.cachedUpdate(Defaults.scala:1419)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1348)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1310)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (*:update) sbt.ResolveException: unresolved dependency: no.vedaadata#sbt-javafx;0.6.2-coinffeine: not found
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?

**Comment by sortega** [comment]
Thanks for noticing it.
You should be able to resolve the artifact now. Can you try again?

**Comment by ayoubmtd** [comment]
Yes, the dependencies are resolved fine now. Thanks for the quick fix.
