### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by MarcoFalke** [Coinffeine/coinffeine#267]
```bash
$ sbt compile test
[info] Loading project definition from /tmp/coinffeine-0.10.1/project
[info] Updating {file:/tmp/coinffeine-0.10.1/project/}coinffeine-0-10-1-build...
[info] Resolving org.scala-sbt.ivy#ivy;2.3.0-sbt-fccfbd44c9f64523b61398a0155784d[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Compiling 4 Scala sources to /tmp/coinffeine-0.10.1/project/target/scala-2.10/sbt-0.13/classes...
References to undefined settings: 

  server/*:release from coinffeine/*:release (/tmp/coinffeine-0.10.1/build.sbt:59)

  okpaymock/*:release from coinffeine/*:release (/tmp/coinffeine-0.10.1/build.sbt:59)
 
	at sbt.Init$class.Uninitialized(Settings.scala:265)
	at sbt.Def$.Uninitialized(Def.scala:10)
	at sbt.Init$class.delegate(Settings.scala:191)
	at sbt.Def$.delegate(Def.scala:10)
	at sbt.Init$class.compiled(Settings.scala:138)
	at sbt.Def$.compiled(Def.scala:10)
	at sbt.Init$class.make(Settings.scala:144)
	at sbt.Def$.make(Def.scala:10)
	at sbt.Load$.apply(Load.scala:135)
	at sbt.Load$.defaultLoad(Load.scala:36)
	at sbt.BuiltinCommands$.doLoadProject(Main.scala:481)
	at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:475)
	at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:475)
	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:58)
	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:58)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:60)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:60)
	at sbt.Command$.process(Command.scala:92)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
	at sbt.State$$anon$1.process(State.scala:184)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.MainLoop$.next(MainLoop.scala:98)
	at sbt.MainLoop$.run(MainLoop.scala:91)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:70)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:65)
	at sbt.Using.apply(Using.scala:24)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:65)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:48)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:32)
	at sbt.MainLoop$.runLogged(MainLoop.scala:24)
	at sbt.StandardMain$.runManaged(Main.scala:53)
	at sbt.xMain.run(Main.scala:28)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
	at xsbt.boot.Boot$.main(Boot.scala:17)
	at xsbt.boot.Boot.main(Boot.scala)
[error] References to undefined settings: 
[error] 
[error]   server/*:release from coinffeine/*:release (/tmp/coinffeine-0.10.1/build.sbt:59)
[error] 
[error]   okpaymock/*:release from coinffeine/*:release (/tmp/coinffeine-0.10.1/build.sbt:59)
[error]  
[error] Use 'last' for the full log.
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? 

````

I never used ```sbt``` before so maybe the issue is on my side?

Also, could you enable travis or something similar?

**Comment by gotoalberto** [comment]
Hello Marco,

We work in a private repository which contains more modules you see in this public repository. 
These modules are private and we don't publish the code because they are related with integration tests and infrastructure. OKPaymock module which appears in your error message is an example, this module is a fake Okpay service to try Coinffeine using tests.

We need to uncouple these modules and extract them into a distinct projects, but while this task is undertaken we publish the code every night cleaning these private modules with a patch in the last commit.

If you want to compile coinffeine please make sure your local git repository is in the latest commit from the remote repository:

```
git pull origin
```

Then you can compile the code using:

```
sbt compile
```

**Comment by MarcoFalke** [comment]
```
[error] 957 errors found
[error] (gui/compile:compileIncremental) Compilation failed
[error] Total time: 164 s, completed Aug 7, 2015 3:19:06 PM
```
Full log here: http://pastebin.com/raw.php?i=czAKQ7NL

Do I need to somehow install javafx? Isn't javafx already in jdk8?
```
$ git pull origin 
Current branch master is up to date.
$ java -version
openjdk version "1.8.0_51"
OpenJDK Runtime Environment (build 1.8.0_51-b16)
OpenJDK 64-Bit Server VM (build 25.51-b03, mixed mode)
```

**Comment by gotoalberto** [comment]
You need Java JDK 1.8u45 to compile Coinffeine. Could you check you have this version?
You can get your installed version using:
```
$ java -version
```

Here the output for this command in my environment:

```
gotoalberto@macbook~/git/coinffeine (master-server)$ java -version
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)
```

**Comment by gotoalberto** [comment]
You need Java JDK 1.8u45 to compile and package Coinffeine.

Please check you have also SBT 0.13 and Protobuf Compiler 2.5. You can check all requirements in our readme file: 
https://github.com/Coinffeine/coinffeine/blob/master/README.md

This is my environment:

```
gotoalberto@macbook~/git/coinffeine$ java -version
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)
```
```
gotoalberto@macbook~/git/coinffeine$ sbt --version
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
sbt launcher version 0.13.2
```
```
gotoalberto@macbook~/git/coinffeine$ protoc --version
libprotoc 2.5.0
```

**Comment by MarcoFalke** [comment]
It says I can also use more recent versions:
```
$ java -version && echo && protoc --version && echo && sbt --version
openjdk version "1.8.0_51"
OpenJDK Runtime Environment (build 1.8.0_51-b16)
OpenJDK 64-Bit Server VM (build 25.51-b03, mixed mode)

libprotoc 2.5.0

sbt launcher version 0.13.8
```

I will try with the older versions maybe tomorrow.

**Comment by gotoalberto** [comment]
Your problem is you are using OpenJDK instead JDK. JavaFX classes are not in OpenJDK.

Please, install JDK and try to compile Coinffeine.

**Comment by MarcoFalke** [comment]
Awesome, thanks for the help! I completely forgot there is OpenJDK installed on my machine as well. Just setting ```-java-home``` fixed the issue:

```
$ sbt -java-home /usr/java/jdk1.8.0_51/jre compile test
$ sbt -java-home /usr/java/jdk1.8.0_51/jre/ gui/run
```
